language: php

php:
  - 5.6
  - 5.7
  - hhvm

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install

script:
 - php ./vendor/bin/phpunit --configuration tests/phpunit.xml
