sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

allow_failures:
  - php: nightly
  - php: hhvm

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install

script:
 - php ./vendor/bin/phpunit --configuration tests/phpunit.xml
